# Use a port different from devservices
http_addr: 0.0.0.0:18888

long_term_storage:
  type: gcs
  endpoint: http://localhost:8087
  bucket: test-bucket

high_volume_storage:
  type: bigtable
  endpoint: localhost:8086
  project_id: testing
  instance_name: objectstore
  table_name: objectstore

logging:
  level: trace
  format: auto

# sentry:
#   dsn: http://<key>@localhost:8000/1
#   sample_rate: 1.0
#   traces_sample_rate: 1.0
#   environment: development

metrics:
  # datadog_key: <API_KEY>
  tags:
    sentry_region: development
