[package]
name = "objectstore-client"
authors = ["Sentry <oss@sentry.io>"]
description = "Client SDK for Objectstore, the Sentry object storage platform"
homepage = "https://getsentry.github.io/objectstore/"
repository = "https://github.com/getsentry/objectstore"
license-file = "../../LICENSE.md"
version = "0.0.5"
edition = "2024"
rust-version = "1.89"
publish = true

[dependencies]
async-compression = { version = "0.4.27", features = ["tokio", "zstd"] }
bytes = { workspace = true }
futures-util = { workspace = true }
objectstore-types = { workspace = true }
reqwest = { workspace = true, features = ["json", "stream"] }
sentry = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["io"] }

[dev-dependencies]
objectstore-server = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "full"] }
uuid = { version = "1.18.0", features = ["v7"] }
zstd = "0.13.3"

[features]
default = ["hickory-dns"]
hickory-dns = ["reqwest/hickory-dns"]
