[package]
name = "objectstore-types"
authors = ["Sentry <oss@sentry.io>"]
description = "Shared types for the Objectstore client and server"
homepage = "https://getsentry.github.io/objectstore/"
repository = "https://github.com/getsentry/objectstore"
license-file = "../LICENSE.md"
version = "0.0.6"
edition = "2024"
publish = true

[dependencies]
anyhow = { workspace = true }
humantime = { workspace = true }
http = { workspace = true }
serde = { workspace = true }
