name: Changelog Preview
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited, labeled]
    paths: ["clients/**"]

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  changelog-preview:
    uses: getsentry/craft/.github/workflows/changelog-preview.yml@v2
    secrets: inherit
